apiVersion: v1
kind: Service
metadata:
  name: transaction
  namespace: global-bank
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: transaction
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction
  namespace: global-bank
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transaction
  template:
    metadata:
      labels:
        app: transaction
    spec:
      containers:
      - image: localhost:32000/brainupgrade/global-bank-transaction:1.0.0
        name: transaction
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: http
        env:
          - name: java.security.egd
            value: file:/dev/./urandom
          - name: server.port
            value: "80"
          - name: spring.datasource.url
            value: jdbc:mariadb://transaction-db.global-bank.svc.cluster.local:3306/transaction
          - name: spring.datasource.driverClassName
            value: "org.mariadb.jdbc.Driver"
          - name: spring.jpa.database-platform
            value: "org.hibernate.dialect.MariaDBDialect"
          - name: spring.jpa.properties.hibernate.dialect
            value: "org.hibernate.dialect.MariaDBDialect"
          - name: spring.datasource.username
            value: "transaction"
          - name: spring.datasource.password
            value: "transaction"
          - name: feign.url-account-service
            value: "account.global-bank.svc.cluster.local/account"
          - name: feign.url-rule-service
            value: "rules.global-bank.svc.cluster.local/rules"
          - name: spring.jpa.hibernate.ddl-auto
            value: "create"  
          - name: spring.jpa.generate-ddl
            value: "true"  